In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
#numpy is for numerical calculations
#pandas is for data analysis
#matplotlib is for data visualization

In [ ]:
abc=np.random.randint(50,100,25)

In [ ]:
abc

array([95, 50, 94, 66, 70, 71, 71, 54, 62, 92, 56, 79, 82, 87, 98, 51, 51,
       62, 51, 94, 78, 64, 58, 98, 93])

In [ ]:
abc=np.random.randint(50,100,size=(5,5))
abc

array([[72, 97, 84, 61, 74],
       [62, 78, 62, 98, 79],
       [63, 74, 82, 51, 94],
       [77, 59, 91, 85, 71],
       [57, 81, 86, 91, 88]])

In [ ]:
c=['Test1','Test2','Test3','Test4','Test5']
i='Anne Brad Charlie Dinesh Enam'.split()

In [ ]:
i

['Anne', 'Brad', 'Charlie', 'Dinesh', 'Enam']

In [ ]:
df1=pd.DataFrame(abc,columns=c,index=i)
df1

Test1  Test2  Test3  Test4  Test5
Anne        72     97     84     61     74
Brad        62     78     62     98     79
Charlie     63     74     82     51     94
Dinesh      77     59     91     85     71
Enam        57     81     86     91     88

In [ ]:
df1['TotalScore']=df1['Test1']+df1['Test2']+df1['Test3']+df1['Test4']+df1['Test5']
df1

Test1  Test2  Test3  Test4  Test5  TotalScore
Anne        72     97     84     61     74         388
Brad        62     78     62     98     79         379
Charlie     63     74     82     51     94         364
Dinesh      77     59     91     85     71         383
Enam        57     81     86     91     88         403

In [ ]:
#assignment
#create a numpy array of 4 rows and 4 columns and generate random numbers
#create 2 two lists
#1st list should contain, names of 4 students
#2nd list should contain column names of each exams
#ultimately create a dataframe with the student names as index, column names and the numpy array valyes as marks
#create a new column which will have total of all the exam marks or each student


In [2]:
marks=np.random.randint(20,50,size=(4,4))
marks

array([[24, 24, 20, 48],
       [36, 44, 40, 28],
       [33, 40, 35, 45],
       [41, 37, 28, 21]])

In [3]:
Subjects=['Math','Biology','Computers','Sports']
names=['John','Peter','Josh','Rob']

In [4]:
df=pd.DataFrame(marks,columns=Subjects,index=names)
df

Math  Biology  Computers  Sports
John     24       24         20      48
Peter    36       44         40      28
Josh     33       40         35      45
Rob      41       37         28      21

In [5]:
df['Total']=df['Math']+df['Biology']+df['Computers']+df['Sports']
df

Math  Biology  Computers  Sports  Total
John     24       24         20      48    116
Peter    36       44         40      28    148
Josh     33       40         35      45    153
Rob      41       37         28      21    127

In [7]:
df['Percentage']=(df['Total']/200)*100
df

Math  Biology  Computers  Sports  Total  Percentage
John     24       24         20      48    116        58.0
Peter    36       44         40      28    148        74.0
Josh     33       40         35      45    153        76.5
Rob      41       37         28      21    127        63.5

In [ ]:
df2=df.drop('Total',axis=1)  #axis=1 specifies removing the columns
df2

Math  Biology  Computers  Sports
John     35       42         23      37
Peter    36       33         28      43
Josh     42       22         23      35
Rob      29       25         21      23

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df1

Test1  Test2  Test3  Test4  Test5  TotalScore
Anne        72     97     84     61     74         388
Brad        62     78     62     98     79         379
Charlie     63     74     82     51     94         364
Dinesh      77     59     91     85     71         383
Enam        57     81     86     91     88         403

In [ ]:
df1=df1.drop('Test5',axis=1)  #drop function is used to remove the rows or columns
df1

Test1  Test2  Test3  Test4  TotalScore
Anne        72     97     84     61         388
Brad        62     78     62     98         379
Charlie     63     74     82     51         364
Dinesh      77     59     91     85         383
Enam        57     81     86     91         403

In [ ]:
df1=df1.drop('Test6',axis=1)  #drop function is used to remove the rows or columns
df1

KeyError: ignored

In [ ]:
df1=df1.drop('Charlie',axis=0)  #drop function is used to remove the rows or columns
df1

Test1  Test2  Test3  Test4  TotalScore
Anne       72     97     84     61         388
Brad       62     78     62     98         379
Dinesh     77     59     91     85         383
Enam       57     81     86     91         403

In [ ]:
#Dataframe with values from a dictionary

In [ ]:
d={'Cricket':[1,3,np.nan,4,6,7,2,np.nan],
   'Baseball':[5,np.nan,np.nan,5,7,4,7,3],
   'Tennis':[1,2,3,4,5,6,7,8]}

In [ ]:
type(d)

dict

In [ ]:
df=pd.DataFrame(d)
df
#NaN - missing values

Cricket  Baseball  Tennis
0      1.0       5.0       1
1      3.0       NaN       2
2      NaN       NaN       3
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       4.0       6
6      2.0       7.0       7
7      NaN       3.0       8

In [ ]:
#handling the missing values
#(1)Drop the rows or columns containing the missing values  (dropna)
#(2)Fill the missing values with 0 or mean or mode or median  (fillna)

In [ ]:
#1. Drop the rows containing the missing values

In [ ]:
df.dropna(axis=0)

Cricket  Baseball  Tennis
0      1.0       5.0       1
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       4.0       6
6      2.0       7.0       7

In [ ]:
#2. Drop the columns containing the missing values

In [ ]:
df.dropna(axis=1)

Tennis
0       1
1       2
2       3
3       4
4       5
5       6
6       7
7       8

In [ ]:
df

Cricket  Baseball  Tennis
0      1.0       5.0       1
1      3.0       NaN       2
2      NaN       NaN       3
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       4.0       6
6      2.0       7.0       7
7      NaN       3.0       8

In [ ]:
df.fillna(value=0)

Cricket  Baseball  Tennis
0      1.0       5.0       1
1      3.0       0.0       2
2      0.0       0.0       3
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       4.0       6
6      2.0       7.0       7
7      0.0       3.0       8

In [ ]:
df

Cricket  Baseball  Tennis
0      1.0       5.0       1
1      3.0       NaN       2
2      NaN       NaN       3
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       4.0       6
6      2.0       7.0       7
7      NaN       3.0       8

In [ ]:
df['Cricket']=df['Cricket'].fillna(value=df['Cricket'].median())

In [ ]:
df

Cricket  Baseball  Tennis
0      1.0       5.0       1
1      3.0       NaN       2
2      3.5       NaN       3
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       4.0       6
6      2.0       7.0       7
7      3.5       3.0       8

In [ ]:
df['Baseball']=df['Baseball'].fillna(value=df['Baseball'].median())
df

Cricket  Baseball  Tennis
0      1.0       5.0       1
1      3.0       5.0       2
2      3.5       5.0       3
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       4.0       6
6      2.0       7.0       7
7      3.5       3.0       8

In [ ]:
df=df.set_index([['Alpha','Bravo','Charlie','Delta','Echo','Foxtrot','Golf','Hotel']])
#set_index is the function used to change the index values
df

Cricket  Baseball  Tennis
Alpha        1.0       5.0       1
Bravo        3.0       5.0       2
Charlie      3.5       5.0       3
Delta        4.0       5.0       4
Echo         6.0       7.0       5
Foxtrot      7.0       4.0       6
Golf         2.0       7.0       7
Hotel        3.5       3.0       8

In [ ]:
df.reset_index(inplace=True)
df

index  Cricket  Baseball  Tennis
0    Alpha      1.0       5.0       1
1    Bravo      3.0       5.0       2
2  Charlie      3.5       5.0       3
3    Delta      4.0       5.0       4
4     Echo      6.0       7.0       5
5  Foxtrot      7.0       4.0       6
6     Golf      2.0       7.0       7
7    Hotel      3.5       3.0       8