<H1>NUMPY</h1>
Numpy stands for Numerical Python

It is a basic and one of the most important libary for numerical computations


Using Numpy we can perform


*  Mathematical and logical operations
*  Fourier transforms
*  Linear Algebra operations
*  Random number generation




In [2]:
import numpy as np

<h2> creating numpy array </h2>

In [3]:
array1 = np.array([1,2,3,4,5,6])

array is an ordered collection of elements of basic data type of a given length


In [4]:
array1

array([1, 2, 3, 4, 5, 6])

In [5]:
type(array1)

numpy.ndarray

In [6]:
array1.dtype

dtype('int64')

In [7]:
arr2=np.array([2,3,5.6,'n'])

In [8]:
arr2

array(['2', '3', '5.6', 'n'], dtype='<U32')

In [10]:
type(arr2)

numpy.ndarray

In [11]:
len(arr2)

4

In [12]:
len(array1)

6

In [18]:
a=np.random.randint(0,50,10)
a

array([37, 26,  5,  1, 25, 22, 44, 23, 11, 31])

In [21]:
?np.sort(a)

print a array of 5 random integers between 10 and 20.
Also  sort it in ascending order

In [23]:
b=np.random.randint(10,20,5)
np.sort(b)

array([10, 12, 13, 13, 15])

In [24]:
np.unique(b)

array([10, 12, 13, 15])

In [25]:
c=np.array([1,2,3,5,3,2,5,6,3])

In [26]:
len(c)

9

In [27]:
d=np.unique(c)

In [28]:
d

array([1, 2, 3, 5, 6])

In [33]:
e=np.append(d,8)
e

array([1, 2, 3, 5, 6, 8])

In [31]:
d

array([1, 2, 3, 5, 6])

In [36]:
f=np.power(d,2)
f

array([ 1,  4,  9, 25, 36])

In [37]:
g=np.power(d,3)
g

array([  1,   8,  27, 125, 216])

In [39]:
h=np.sqrt(f)
h

array([1., 2., 3., 5., 6.])

In [40]:
np.sqrt(d)

array([1.        , 1.41421356, 1.73205081, 2.23606798, 2.44948974])

In [50]:
np.ones(2)

array([1., 1.])

In [51]:
np.ones(3)

array([1., 1., 1.])

In [52]:
np.ones([1,1])

array([[1.]])

In [53]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [54]:
np.ones([1,3])

array([[1., 1., 1.]])

In [55]:
np.ones([3,1])

array([[1.],
       [1.],
       [1.]])

In [56]:
np.zeros([3,1])

array([[0.],
       [0.],
       [0.]])

In [57]:
np.zeros([1,3])

array([[0., 0., 0.]])

In [62]:
ones=np.ones([4,5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [66]:
fives=ones*5
fives

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [67]:
(np.ones([2,2]))*2.5

array([[2.5, 2.5],
       [2.5, 2.5]])

In [69]:
a=np.array([1,2,3,5,])
a

array([1, 2, 3, 5])

In [70]:
a.shape

(4,)

In [77]:
a.ndim

1

In [80]:
a.size

4

In [83]:
b=np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [75]:
b.shape

(2, 4)

In [76]:
b.ndim

2

In [78]:
b.size

8

In [81]:
b.dtype

dtype('int64')

In [84]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [85]:
b.shape

(2, 4)

In [86]:
c=b.reshape(4,2)
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [87]:
c.shape

(4, 2)

In [97]:
np.random.rand(5)

array([0.83261985, 0.77815675, 0.87001215, 0.97861834, 0.79915856])

In [100]:
np.random.seed(3)
np.random.rand(4,3)

array([[0.5507979 , 0.70814782, 0.29090474],
       [0.51082761, 0.89294695, 0.89629309],
       [0.12558531, 0.20724288, 0.0514672 ],
       [0.44080984, 0.02987621, 0.45683322]])

OTP Generation

In [114]:
np.random.randint(0,10,6)

array([7, 0, 0, 9, 1, 7])

In [115]:
#create 2D array of 35 random int elements beween 100 and 150

In [116]:
a11=np.random.randint(100,150,35)

In [117]:
a11.reshape(7,5)

array([[124, 111, 120, 110, 148],
       [116, 112, 104, 144, 144],
       [119, 116, 134, 139, 101],
       [135, 145, 101, 118, 102],
       [123, 135, 120, 117, 122],
       [128, 143, 107, 133, 143],
       [132, 128, 116, 127, 143]])

In [119]:
a12=np.random.randint(100,150,(7,5))
a12

array([[132, 123, 124, 133, 121],
       [126, 115, 128, 111, 141],
       [117, 107, 113, 131, 104],
       [130, 141, 113, 113, 132],
       [124, 147, 136, 142, 121],
       [106, 123, 128, 112, 128],
       [147, 146, 110, 111, 135]])

In [121]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [125]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [126]:
np.eye(5,k=1,dtype=int)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [129]:
np.eye(4,5,k=-1,dtype=int)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [130]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [135]:
np.arange(3,31,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [136]:
np.arange(-5,-1,1)

array([-5, -4, -3, -2])

In [138]:
np.arange(-5,-1)

array([-5, -4, -3, -2])

In [139]:
np.arange(-5,6,3)

array([-5, -2,  1,  4])

In [140]:
np.arange(5,1,-1)

array([5, 4, 3, 2])

In [142]:
np.arange(30,-31,-3)

array([ 30,  27,  24,  21,  18,  15,  12,   9,   6,   3,   0,  -3,  -6,
        -9, -12, -15, -18, -21, -24, -27, -30])

In [143]:
np.arange(2,2)

array([], dtype=int64)

In [144]:
np.arange(8,2,1)

array([], dtype=int64)

In [145]:
np.arange(10,dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [147]:
np.arange(10,dtype=np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [148]:
np.arange(10,dtype=np.int8)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [149]:
np.arange(10,dtype=np.uint8)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [150]:
np.arange(10,dtype=np.uint16)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint16)

<h3>Matrix</h3>

In [152]:
mat1=np.matrix("1,2,3;4,5,6;7,8,9")
mat1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [153]:
type(mat1)

numpy.matrix

In [154]:
mat2=np.matrix("11,12,13;14,15,16;17,18,19")
mat2

matrix([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])

In [155]:
np.add(mat1,mat2)

matrix([[12, 14, 16],
        [18, 20, 22],
        [24, 26, 28]])

In [156]:
np.subtract(mat1,mat2)

matrix([[-10, -10, -10],
        [-10, -10, -10],
        [-10, -10, -10]])

In [157]:
np.dot(mat1,mat2)

matrix([[ 90,  96, 102],
        [216, 231, 246],
        [342, 366, 390]])

In [158]:
np.multiply(mat1,mat2)

matrix([[ 11,  24,  39],
        [ 56,  75,  96],
        [119, 144, 171]])

In [159]:
np.divide(mat1,mat2)

matrix([[0.09090909, 0.16666667, 0.23076923],
        [0.28571429, 0.33333333, 0.375     ],
        [0.41176471, 0.44444444, 0.47368421]])

In [160]:
np.remainder(mat1,mat2)

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [161]:
arr = np.array([1,5,4,8,3,7])

In [162]:
np.max(arr)

8

In [163]:
np.min(arr)

1